description: "Practice second thought on your automatic thoughts"
command: "help"
name: "second-thoughts"
enable: true
items:
  situation: "发生了什么事情？"
  mood: "在这种情况下，你的情绪如何？程度怎样？（非常厉害，一般，轻微）"
  thought: "你注意到自己有哪些思维或想法？对这些想法的相信程度怎么样？"
  evidence: "你有什么证据支持你认为的是真的吗?有多大概率？"
  worst_case: "最糟糕的结果是什么？"
  best_case: "最好的结果是什么？"
  realistic_case: "最现实的结果是什么？"
  alternative: "Is there an alternative explanation?"
  firend: "What would you tell a friend in this situation?"
  other: "在上面对思维进行评价时，是否有其他衍生的想法？以及对这些想法的相信程度？" 
  doing: "最后比较客观地看待这件事情，你觉得你应该怎么做？"